name: yolov4
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - tqdm
  - pytorch
  - ipykernel
  - opencv
  - torchvision
  - matplotlib
  - scipy
  - pip:
    - git+https://github.com/cshubhamrao/mish-cuda.git
    - pyyaml
    - gdown
